from .acmeSupplierSchema import AcmeSupplierSchema
from .paperfliesSupplierSchema import PaperfliesSupplierSchema
from .patagoniaSupplierSchema import PatagoniaSupplierSchema
from ..mergedHotelSchema import MergedHotelSchema
